export const playersData = [
  {
    id: "messi",
    name: "Lionel Messi",
    position: "Forward",
    number: "10",
    photo: "https://i.pinimg.com/736x/cb/55/90/cb5590bcca9becc9b0f8e98f3998bdb9.jpg",
    age: 38,
    nationality: "Argentina",
    countryCode: "AR",
    goals: 28,
    assists: 18,
    matches: 34,
    rating: 8.7,
    dateJoined: "2023-07-15",
    preferredFoot: "Left",
    weight: "72 kg",
    agent: "Jorge Messi",
    height: "170 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "ronaldo",
    name: "Cristiano Ronaldo",
    position: "Forward",
    number: "7",
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGn3P57OEBPNKcBKUo9God-YsaM6a5Kw-LTw&s",
    age: 41,
    nationality: "Portugal",
    countryCode: "PT",
    goals: 31,
    assists: 9,
    matches: 36,
    rating: 8.4,
    dateJoined: "2023-01-01",
    preferredFoot: "Right",
    weight: "83 kg",
    agent: "Gestifute",
    height: "187 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "kylian",
    name: "Kylian Mbappe",
    position: "Forward",
    number: "7",
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnIzhxmS9_y53ItYNfmvxKtKbjJs6MRlKhew&s",
    age: 27,
    nationality: "France",
    countryCode: "FR",
    goals: 33,
    assists: 11,
    matches: 38,
    rating: 8.6,
    dateJoined: "2017-07-01",
    preferredFoot: "Right",
    weight: "73 kg",
    agent: "Interconnected Sports",
    height: "178 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "haaland",
    name: "Erling Haaland",
    position: "Forward",
    number: "9",
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrNrYRkh4mlKDXs3eUpR7zCLUPUvBsJLEQvQ&s",
    age: 25,
    nationality: "Norway",
    countryCode: "NO",
    goals: 35,
    assists: 6,
    matches: 37,
    rating: 8.5,
    dateJoined: "2022-07-01",
    preferredFoot: "Left",
    weight: "88 kg",
    agent: "Raiola / Team",
    height: "195 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "debruyne",
    name: "Kevin De Bruyne",
    position: "Midfielder",
    number: "17",
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8ZEJgwWxC5l36dSoSkDMPlTrhfSk1aHr90w&s",
    age: 34,
    nationality: "Belgium",
    countryCode: "BE",
    goals: 10,
    assists: 18,
    matches: 32,
    rating: 8.2,
    dateJoined: "2015-08-30",
    preferredFoot: "Right",
    weight: "70 kg",
    agent: "Roc Nation Sports",
    height: "181 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "salah",
    name: "Mohamed Salah",
    position: "Forward",
    number: "11",
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9wGQV0uU2JXTqztsC_g8fz9_cfLXquCMU2A&s",
    age: 33,
    nationality: "Egypt",
    countryCode: "EG",
    goals: 24,
    assists: 10,
    matches: 35,
    rating: 8.1,
    dateJoined: "2017-06-22",
    preferredFoot: "Left",
    weight: "71 kg",
    agent: "Ramy Abbas Issa",
    height: "175 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "kane",
    name: "Harry Kane",
    position: "Forward",
    number: "9",
    photo: "https://img.uefa.com/imgml/TP/players/17/2026/324x324/250016833.jpg",
    age: 32,
    nationality: "England",
    countryCode: "GB",
    goals: 29,
    assists: 8,
    matches: 34,
    rating: 8.2,
    dateJoined: "2023-08-12",
    preferredFoot: "Right",
    weight: "86 kg",
    agent: "CK66",
    height: "188 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "lewandowski",
    name: "Robert Lewandowski",
    position: "Forward",
    number: "9",
    photo: "https://img.uefa.com/imgml/TP/players/17/2026/324x324/250002096.jpg",
    age: 37,
    nationality: "Poland",
    countryCode: "PL",
    goals: 25,
    assists: 7,
    matches: 33,
    rating: 8.0,
    dateJoined: "2022-07-19",
    preferredFoot: "Right",
    weight: "81 kg",
    agent: "Gol International",
    height: "185 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "benzema",
    name: "Karim Benzema",
    position: "Forward",
    number: "9",
    photo: "https://www.fifarosters.com/assets/players/fifa20/faces/165153.png",
    age: 38,
    nationality: "France",
    countryCode: "FR",
    goals: 21,
    assists: 6,
    matches: 29,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "81 kg",
    agent: "Karim Djaziri",
    height: "185 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "viniciusjr",
    name: "Vinicius Jr.",
    position: "Forward",
    number: "7",
    photo: "https://b.fssta.com/uploads/application/soccer/headshots/53004.png",
    age: 25,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 19,
    assists: 14,
    matches: 36,
    rating: 8.3,
    dateJoined: "2018-07-20",
    preferredFoot: "Right",
    weight: "73 kg",
    agent: "Roc Nation Sports",
    height: "176 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "son",
    name: "Son Heung-min",
    position: "Forward",
    number: "7",
    photo: "https://images.weserv.nl/?url=www.footyrenders.com/render/son-heung-min-37-390x492.png",
    age: 33,
    nationality: "South Korea",
    countryCode: "KR",
    goals: 18,
    assists: 9,
    matches: 34,
    rating: 7.9,
    dateJoined: "2015-08-28",
    preferredFoot: "Both",
    weight: "77 kg",
    agent: "CAA Sports",
    height: "183 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "saka",
    name: "Bukayo Saka",
    position: "Forward",
    number: "7",
    photo: "https://images.weserv.nl/?url=www.footyrenders.com/render/bukayo-saka-7-390x379.png",
    age: 24,
    nationality: "England",
    countryCode: "GB",
    goals: 16,
    assists: 12,
    matches: 37,
    rating: 8.0,
    dateJoined: "2018-01-01",
    preferredFoot: "Left",
    weight: "65 kg",
    agent: "Elite Project Group",
    height: "178 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "lautaro",
    name: "Lautaro Martinez",
    position: "Forward",
    number: "10",
    photo: "https://b.fssta.com/uploads/application/soccer/headshots/39831.png",
    age: 28,
    nationality: "Argentina",
    countryCode: "AR",
    goals: 23,
    assists: 6,
    matches: 35,
    rating: 8.0,
    dateJoined: "2018-07-04",
    preferredFoot: "Right",
    weight: "72 kg",
    agent: "Alejandro Camano",
    height: "174 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "darwin",
    name: "Darwin Nunez",
    position: "Forward",
    number: "9",
    photo: "https://cdn-img.zerozero.pt/img/planteis/new/14/75/8721475_darwin_nunez_20251211021518.jpg",
    age: 26,
    nationality: "Uruguay",
    countryCode: "UY",
    goals: 17,
    assists: 7,
    matches: 36,
    rating: 7.6,
    dateJoined: "2022-06-14",
    preferredFoot: "Right",
    weight: "81 kg",
    agent: "Gestifute",
    height: "187 cm",
    contractExpires: "2028-06-30",
  },

  {
    id: "osimhen",
    name: "Victor Osimhen",
    position: "Forward",
    number: "9",
    photo: "https://img.uefa.com/imgml/TP/players/1/2026/324x324/250132987.jpg",
    age: 27,
    nationality: "Nigeria",
    countryCode: "NG",
    goals: 22,
    assists: 5,
    matches: 31,
    rating: 7.9,
    dateJoined: "2020-09-01",
    preferredFoot: "Right",
    weight: "78 kg",
    agent: "ROOF",
    height: "186 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "neymar",
    name: "Neymar Jr.",
    position: "Forward",
    number: "10",
    photo: "https://i.pinimg.com/736x/e9/11/5a/e9115a133e8b8b08b8ac441fca0e1162.jpg",
    age: 34,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 14,
    assists: 12,
    matches: 26,
    rating: 7.8,
    dateJoined: "2023-08-15",
    preferredFoot: "Right",
    weight: "68 kg",
    agent: "NR Sports",
    height: "175 cm",
    contractExpires: "2026-06-30",
  },
];