export const playersData = [
  {
    id: "messi",
    name: "Lionel Messi",
    position: "Forward",
    number: "10",
    isActive: true,
    photo: "https://www.fifarosters.com/assets/players/fifa20/faces/158023.png",
    age: 38,
    nationality: "Argentina",
    countryCode: "AR",
    goals: 28,
    assists: 18,
    matches: 34,
    rating: 8.7,
    dateJoined: "2023-07-15",
    preferredFoot: "Left",
    weight: "72 kg",
    agent: "Jorge Messi",
    height: "170 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "ronaldo",
    name: "Cristiano Ronaldo",
    position: "Forward",
    number: "7",
    isActive: true,
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGn3P57OEBPNKcBKUo9God-YsaM6a5Kw-LTw&s",
    age: 41,
    nationality: "Portugal",
    countryCode: "PT",
    goals: 31,
    assists: 9,
    matches: 36,
    rating: 8.4,
    dateJoined: "2023-01-01",
    preferredFoot: "Right",
    weight: "83 kg",
    agent: "Gestifute",
    height: "187 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "kylian",
    name: "Kylian Mbappe",
    position: "Forward",
    number: "7",
    isActive: true,
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnIzhxmS9_y53ItYNfmvxKtKbjJs6MRlKhew&s",
    age: 27,
    nationality: "France",
    countryCode: "FR",
    goals: 33,
    assists: 11,
    matches: 38,
    rating: 8.6,
    dateJoined: "2017-07-01",
    preferredFoot: "Right",
    weight: "73 kg",
    agent: "Interconnected Sports",
    height: "178 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "haaland",
    name: "Erling Haaland",
    position: "Forward",
    number: "9",
    isActive: true,
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrNrYRkh4mlKDXs3eUpR7zCLUPUvBsJLEQvQ&s",
    age: 25,
    nationality: "Norway",
    countryCode: "NO",
    goals: 35,
    assists: 6,
    matches: 37,
    rating: 8.5,
    dateJoined: "2022-07-01",
    preferredFoot: "Left",
    weight: "88 kg",
    agent: "Raiola / Team",
    height: "195 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "debruyne",
    name: "Kevin De Bruyne",
    position: "Midfielder",
    number: "17",
    isActive: true,
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8ZEJgwWxC5l36dSoSkDMPlTrhfSk1aHr90w&s",
    age: 34,
    nationality: "Belgium",
    countryCode: "BE",
    goals: 10,
    assists: 18,
    matches: 32,
    rating: 8.2,
    dateJoined: "2015-08-30",
    preferredFoot: "Right",
    weight: "70 kg",
    agent: "Roc Nation Sports",
    height: "181 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "salah",
    name: "Mohamed Salah",
    position: "Forward",
    number: "11",
    isActive: true,
    photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9wGQV0uU2JXTqztsC_g8fz9_cfLXquCMU2A&s",
    age: 33,
    nationality: "Egypt",
    countryCode: "EG",
    goals: 24,
    assists: 10,
    matches: 35,
    rating: 8.1,
    dateJoined: "2017-06-22",
    preferredFoot: "Left",
    weight: "71 kg",
    agent: "Ramy Abbas Issa",
    height: "175 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "kane",
    name: "Harry Kane",
    position: "Forward",
    number: "9",
    isActive: true,
    photo: "https://img.uefa.com/imgml/TP/players/17/2026/324x324/250016833.jpg",
    age: 32,
    nationality: "England",
    countryCode: "GB",
    goals: 29,
    assists: 8,
    matches: 34,
    rating: 8.2,
    dateJoined: "2023-08-12",
    preferredFoot: "Right",
    weight: "86 kg",
    agent: "CK66",
    height: "188 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "lewandowski",
    name: "Robert Lewandowski",
    position: "Forward",
    number: "9",
    isActive: true,
    photo: "https://img.uefa.com/imgml/TP/players/17/2026/324x324/250002096.jpg",
    age: 37,
    nationality: "Poland",
    countryCode: "PL",
    goals: 25,
    assists: 7,
    matches: 33,
    rating: 8.0,
    dateJoined: "2022-07-19",
    preferredFoot: "Right",
    weight: "81 kg",
    agent: "Gol International",
    height: "185 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "benzema",
    name: "Karim Benzema",
    position: "Forward",
    number: "9",
    isActive: true,
    photo: "https://www.fifarosters.com/assets/players/fifa20/faces/165153.png",
    age: 38,
    nationality: "France",
    countryCode: "FR",
    goals: 21,
    assists: 6,
    matches: 29,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "81 kg",
    agent: "Karim Djaziri",
    height: "185 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "viniciusjr",
    name: "Vinicius Jr.",
    position: "Forward",
    number: "7",
    isActive: true,
    photo: "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/238794.png&bg=FFFFFF&fit=cover&output=png",
    age: 25,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 19,
    assists: 14,
    matches: 36,
    rating: 8.3,
    dateJoined: "2018-07-20",
    preferredFoot: "Right",
    weight: "73 kg",
    agent: "Roc Nation Sports",
    height: "176 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "son",
    name: "Son Heung-min",
    position: "Forward",
    number: "7",
    isActive: true,
    photo: "https://cdn3.futbin.com/content/fifa25/img/players/200104.png?fm=png&ixlib=java-2.1.0&verzion=2&w=512&s=f2a00104083f105c7a563460d7e9cdf9",
    age: 33,
    nationality: "South Korea",
    countryCode: "KR",
    goals: 18,
    assists: 9,
    matches: 34,
    rating: 7.9,
    dateJoined: "2015-08-28",
    preferredFoot: "Both",
    weight: "77 kg",
    agent: "CAA Sports",
    height: "183 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "saka",
    name: "Bukayo Saka",
    position: "Forward",
    number: "7",
    isActive: true,
    photo: "https://images.weserv.nl/?url=www.footyrenders.com/render/bukayo-saka-7-390x379.png",
    age: 24,
    nationality: "England",
    countryCode: "GB",
    goals: 16,
    assists: 12,
    matches: 37,
    rating: 8.0,
    dateJoined: "2018-01-01",
    preferredFoot: "Left",
    weight: "65 kg",
    agent: "Elite Project Group",
    height: "178 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "lautaro",
    name: "Lautaro Martinez",
    position: "Forward",
    number: "10",
    isActive: true,
    photo: "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/231478.png&bg=FFFFFF&fit=cover&output=png",
    age: 28,
    nationality: "Argentina",
    countryCode: "AR",
    goals: 23,
    assists: 6,
    matches: 35,
    rating: 8.0,
    dateJoined: "2018-07-04",
    preferredFoot: "Right",
    weight: "72 kg",
    agent: "Alejandro Camano",
    height: "174 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "darwin",
    name: "Darwin Nunez",
    position: "Forward",
    number: "9",
    isActive: true,
    photo: "https://cdn-img.zerozero.pt/img/planteis/new/14/75/8721475_darwin_nunez_20251211021518.jpg",
    age: 26,
    nationality: "Uruguay",
    countryCode: "UY",
    goals: 17,
    assists: 7,
    matches: 36,
    rating: 7.6,
    dateJoined: "2022-06-14",
    preferredFoot: "Right",
    weight: "81 kg",
    agent: "Gestifute",
    height: "187 cm",
    contractExpires: "2028-06-30",
  },

  {
    id: "osimhen",
    name: "Victor Osimhen",
    position: "Forward",
    number: "9",
    isActive: true,
    photo: "https://img.uefa.com/imgml/TP/players/1/2026/324x324/250132987.jpg",
    age: 27,
    nationality: "Nigeria",
    countryCode: "NG",
    goals: 22,
    assists: 5,
    matches: 31,
    rating: 7.9,
    dateJoined: "2020-09-01",
    preferredFoot: "Right",
    weight: "78 kg",
    agent: "ROOF",
    height: "186 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "neymar",
    name: "Neymar Jr.",
    position: "Forward",
    number: "10",
    isActive: true,
    photo: "https://i.pinimg.com/736x/e9/11/5a/e9115a133e8b8b08b8ac441fca0e1162.jpg",
    age: 34,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 14,
    assists: 12,
    matches: 26,
    rating: 7.8,
    dateJoined: "2023-08-15",
    preferredFoot: "Right",
    weight: "68 kg",
    agent: "NR Sports",
    height: "175 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "modric",
    name: "Luka Modric",
    position: "Midfielder",
    number: "10",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/177003.png&bg=FFFFFF&fit=cover&output=png",
    age: 40,
    nationality: "Croatia",
    countryCode: "HR",
    goals: 6,
    assists: 10,
    matches: 32,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "66 kg",
    agent: "NIKE / Family",
    height: "172 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "rodri",
    name: "Rodri",
    position: "Midfielder",
    number: "16",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/231866.png&bg=FFFFFF&fit=cover&output=png",
    age: 29,
    nationality: "Spain",
    countryCode: "ES",
    goals: 8,
    assists: 7,
    matches: 35,
    rating: 8.3,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "82 kg",
    agent: "LEADERBROCK",
    height: "191 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "vandijk",
    name: "Virgil van Dijk",
    position: "Defender",
    number: "4",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/203376.png&bg=FFFFFF&fit=cover&output=png",
    age: 34,
    nationality: "Netherlands",
    countryCode: "NL",
    goals: 5,
    assists: 2,
    matches: 33,
    rating: 8.1,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "92 kg",
    agent: "ROOF",
    height: "193 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "ramos",
    name: "Sergio Ramos",
    position: "Defender",
    number: "4",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/155862.png&bg=FFFFFF&fit=cover&output=png",
    age: 40,
    nationality: "Spain",
    countryCode: "ES",
    goals: 4,
    assists: 1,
    matches: 28,
    rating: 7.7,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "82 kg",
    agent: "Ramos / Family",
    height: "184 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "alisson",
    name: "Alisson Becker",
    position: "Goalkeeper",
    number: "1",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/212831.png&bg=FFFFFF&fit=cover&output=png",
    age: 33,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 0,
    assists: 1,
    matches: 34,
    rating: 8.0,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "91 kg",
    agent: "Bertolucci Sports",
    height: "191 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "courtois",
    name: "Thibaut Courtois",
    position: "Goalkeeper",
    number: "1",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/192119.png&bg=FFFFFF&fit=cover&output=png",
    age: 34,
    nationality: "Belgium",
    countryCode: "BE",
    goals: 0,
    assists: 0,
    matches: 30,
    rating: 8.2,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "96 kg",
    agent: "Gol International",
    height: "200 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "kante",
    name: "N'Golo Kante",
    position: "Midfielder",
    number: "7",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/215914.png&bg=FFFFFF&fit=cover&output=png",
    age: 35,
    nationality: "France",
    countryCode: "FR",
    goals: 4,
    assists: 6,
    matches: 33,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "70 kg",
    agent: "SportCover",
    height: "168 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "pogba",
    name: "Paul Pogba",
    position: "Midfielder",
    number: "6",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/195864.png&bg=FFFFFF&fit=cover&output=png",
    age: 33,
    nationality: "France",
    countryCode: "FR",
    goals: 7,
    assists: 9,
    matches: 30,
    rating: 7.8,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "84 kg",
    agent: "Raiola / Team",
    height: "191 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "kimmich",
    name: "Joshua Kimmich",
    position: "Midfielder",
    number: "6",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/212622.png&bg=FFFFFF&fit=cover&output=png",
    age: 31,
    nationality: "Germany",
    countryCode: "DE",
    goals: 5,
    assists: 12,
    matches: 35,
    rating: 8.2,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "75 kg",
    agent: "11WINS",
    height: "176 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "kroos",
    name: "Toni Kroos",
    position: "Midfielder",
    number: "8",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/182521.png&bg=FFFFFF&fit=cover&output=png",
    age: 36,
    nationality: "Germany",
    countryCode: "DE",
    goals: 4,
    assists: 11,
    matches: 32,
    rating: 8.1,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "76 kg",
    agent: "Sports360",
    height: "183 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "casemiro",
    name: "Casemiro",
    position: "Midfielder",
    number: "18",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/200145.png&bg=FFFFFF&fit=cover&output=png",
    age: 34,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 6,
    assists: 4,
    matches: 34,
    rating: 8.0,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "84 kg",
    agent: "BEST OF YOU",
    height: "185 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "busquets",
    name: "Sergio Busquets",
    position: "Midfielder",
    number: "5",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/189513.png&bg=FFFFFF&fit=cover&output=png",
    age: 37,
    nationality: "Spain",
    countryCode: "ES",
    goals: 2,
    assists: 6,
    matches: 31,
    rating: 7.8,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "76 kg",
    agent: "Toldra Consulting",
    height: "189 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "neuer",
    name: "Manuel Neuer",
    position: "Goalkeeper",
    number: "1",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/167495.png&bg=FFFFFF&fit=cover&output=png",
    age: 40,
    nationality: "Germany",
    countryCode: "DE",
    goals: 0,
    assists: 0,
    matches: 31,
    rating: 8.1,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "92 kg",
    agent: "ROOF",
    height: "193 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "oblak",
    name: "Jan Oblak",
    position: "Goalkeeper",
    number: "13",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/200389.png&bg=FFFFFF&fit=cover&output=png",
    age: 33,
    nationality: "Slovenia",
    countryCode: "SI",
    goals: 0,
    assists: 0,
    matches: 33,
    rating: 8.2,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "87 kg",
    agent: "Interstellar",
    height: "188 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "terstegen",
    name: "Marc-Andre ter Stegen",
    position: "Goalkeeper",
    number: "1",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/192448.png&bg=FFFFFF&fit=cover&output=png",
    age: 34,
    nationality: "Germany",
    countryCode: "DE",
    goals: 0,
    assists: 1,
    matches: 32,
    rating: 8.0,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "85 kg",
    agent: "ROOF",
    height: "187 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "chiellini",
    name: "Giorgio Chiellini",
    position: "Defender",
    number: "3",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/138956.png&bg=FFFFFF&fit=cover&output=png",
    age: 41,
    nationality: "Italy",
    countryCode: "IT",
    goals: 2,
    assists: 1,
    matches: 26,
    rating: 7.6,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "85 kg",
    agent: "CAA Base",
    height: "187 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "bonucci",
    name: "Leonardo Bonucci",
    position: "Defender",
    number: "19",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/184344.png&bg=FFFFFF&fit=cover&output=png",
    age: 39,
    nationality: "Italy",
    countryCode: "IT",
    goals: 3,
    assists: 1,
    matches: 29,
    rating: 7.7,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "85 kg",
    agent: "World Soccer Agency",
    height: "190 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "marcelo",
    name: "Marcelo",
    position: "Defender",
    number: "12",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/176676.png&bg=FFFFFF&fit=cover&output=png",
    age: 38,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 2,
    assists: 7,
    matches: 30,
    rating: 7.7,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "80 kg",
    agent: "Brazil Soccer",
    height: "174 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "griezmann",
    name: "Antoine Griezmann",
    position: "Forward",
    number: "7",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/194765.png&bg=FFFFFF&fit=cover&output=png",
    age: 35,
    nationality: "France",
    countryCode: "FR",
    goals: 17,
    assists: 10,
    matches: 35,
    rating: 8.1,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "73 kg",
    agent: "By&N Sports",
    height: "176 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "suarez",
    name: "Luis Suarez",
    position: "Forward",
    number: "9",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/176580.png&bg=FFFFFF&fit=cover&output=png",
    age: 39,
    nationality: "Uruguay",
    countryCode: "UY",
    goals: 20,
    assists: 7,
    matches: 32,
    rating: 8.0,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "83 kg",
    agent: "Relatives / Family",
    height: "182 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "hazard",
    name: "Eden Hazard",
    position: "Forward",
    number: "7",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/183277.png&bg=FFFFFF&fit=cover&output=png",
    age: 35,
    nationality: "Belgium",
    countryCode: "BE",
    goals: 12,
    assists: 11,
    matches: 30,
    rating: 7.8,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "74 kg",
    agent: "ROOF",
    height: "175 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "dybala",
    name: "Paulo Dybala",
    position: "Forward",
    number: "21",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/211110.png&bg=FFFFFF&fit=cover&output=png",
    age: 32,
    nationality: "Argentina",
    countryCode: "AR",
    goals: 16,
    assists: 8,
    matches: 31,
    rating: 8.0,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "75 kg",
    agent: "Star Factory",
    height: "177 cm",
    contractExpires: "2027-06-30",
  },

  {
    id: "reus",
    name: "Marco Reus",
    position: "Midfielder",
    number: "11",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/188350.png&bg=FFFFFF&fit=cover&output=png",
    age: 36,
    nationality: "Germany",
    countryCode: "DE",
    goals: 14,
    assists: 9,
    matches: 29,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "71 kg",
    agent: "Sports360",
    height: "180 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "muller",
    name: "Thomas Muller",
    position: "Forward",
    number: "25",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/189596.png&bg=FFFFFF&fit=cover&output=png",
    age: 36,
    nationality: "Germany",
    countryCode: "DE",
    goals: 13,
    assists: 10,
    matches: 33,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "75 kg",
    agent: "ROOF",
    height: "186 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "pique",
    name: "Gerard Pique",
    position: "Defender",
    number: "3",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/152729.png&bg=FFFFFF&fit=cover&output=png",
    age: 39,
    nationality: "Spain",
    countryCode: "ES",
    goals: 2,
    assists: 1,
    matches: 28,
    rating: 7.6,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "85 kg",
    agent: "Kosmos",
    height: "194 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "jordialba",
    name: "Jordi Alba",
    position: "Defender",
    number: "18",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/189332.png&bg=FFFFFF&fit=cover&output=png",
    age: 37,
    nationality: "Spain",
    countryCode: "ES",
    goals: 3,
    assists: 10,
    matches: 32,
    rating: 7.8,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "68 kg",
    agent: "Toldra Consulting",
    height: "170 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "danialves",
    name: "Dani Alves",
    position: "Defender",
    number: "2",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/159261.png&bg=FFFFFF&fit=cover&output=png",
    age: 43,
    nationality: "Brazil",
    countryCode: "BR",
    goals: 1,
    assists: 6,
    matches: 26,
    rating: 7.4,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "70 kg",
    agent: "Brazil Soccer",
    height: "172 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "aguero",
    name: "Sergio Aguero",
    position: "Forward",
    number: "10",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/153079.png&bg=FFFFFF&fit=cover&output=png",
    age: 37,
    nationality: "Argentina",
    countryCode: "AR",
    goals: 18,
    assists: 6,
    matches: 28,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "70 kg",
    agent: "Score Agencies",
    height: "173 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "ibrahimovic",
    name: "Zlatan Ibrahimovic",
    position: "Forward",
    number: "11",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/41236.png&bg=FFFFFF&fit=cover&output=png",
    age: 44,
    nationality: "Sweden",
    countryCode: "SE",
    goals: 19,
    assists: 5,
    matches: 27,
    rating: 7.8,
    dateJoined: "2023-07-01",
    preferredFoot: "Right",
    weight: "95 kg",
    agent: "Mino Raiola",
    height: "195 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "dimaria",
    name: "Angel Di Maria",
    position: "Midfielder",
    number: "11",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/183898.png&bg=FFFFFF&fit=cover&output=png",
    age: 38,
    nationality: "Argentina",
    countryCode: "AR",
    goals: 10,
    assists: 12,
    matches: 33,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "75 kg",
    agent: "DC / Family",
    height: "180 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "james",
    name: "James Rodriguez",
    position: "Midfielder",
    number: "10",
    isActive: true,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/198710.png&bg=FFFFFF&fit=cover&output=png",
    age: 34,
    nationality: "Colombia",
    countryCode: "CO",
    goals: 9,
    assists: 11,
    matches: 31,
    rating: 7.8,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "75 kg",
    agent: "Gestifute",
    height: "180 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "bale",
    name: "Gareth Bale",
    position: "Forward",
    number: "11",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/173731.png&bg=FFFFFF&fit=cover&output=png",
    age: 36,
    nationality: "Wales",
    countryCode: "GB",
    goals: 15,
    assists: 7,
    matches: 29,
    rating: 7.8,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "81 kg",
    agent: "Stellar Group",
    height: "185 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "davidsilva",
    name: "David Silva",
    position: "Midfielder",
    number: "21",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/168542.png&bg=FFFFFF&fit=cover&output=png",
    age: 40,
    nationality: "Spain",
    countryCode: "ES",
    goals: 7,
    assists: 13,
    matches: 32,
    rating: 8.0,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "67 kg",
    agent: "IG Soccer",
    height: "173 cm",
    contractExpires: "2026-06-30",
  },

  {
    id: "ozil",
    name: "Mesut Ozil",
    position: "Midfielder",
    number: "10",
    isActive: false,
    photo:
      "https://images.weserv.nl/?url=www.fifarosters.com/assets/players/fifa20/faces/176635.png&bg=FFFFFF&fit=cover&output=png",
    age: 37,
    nationality: "Germany",
    countryCode: "DE",
    goals: 8,
    assists: 14,
    matches: 31,
    rating: 7.9,
    dateJoined: "2023-07-01",
    preferredFoot: "Left",
    weight: "76 kg",
    agent: "Family / Direct",
    height: "180 cm",
    contractExpires: "2026-06-30",
  },
];