const SAMPLE_FLASHCARDS = {
  response_code: 0,
  results: [
    {
      type: "multiple",
      difficulty: "easy",
      category: "General Knowledge",
      question: "What is Ejay's Favorite Food?",
      correct_answer: "White Rice and Stew",
      incorrect_answers: ["Beans and Plaintain", "Yam", "Whataburger"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Mythology",
      question: "Who killed Goliath?",
      correct_answer: "David",
      incorrect_answers: ["Ejay", "Clement"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Geography",
      question: "What is the capital of France?",
      correct_answer: "Paris",
      incorrect_answers: ["London", "Berlin", "Madrid"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science & Nature",
      question: "What planet is known as the Red Planet?",
      correct_answer: "Mars",
      incorrect_answers: ["Venus", "Jupiter", "Saturn"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Geography",
      question: "How many continents are there?",
      correct_answer: "Seven",
      incorrect_answers: ["Five", "Six", "Eight"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Geography",
      question: "What is the largest ocean on Earth?",
      correct_answer: "Pacific",
      incorrect_answers: ["Atlantic", "Indian", "Arctic"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Art",
      question: "Who wrote Romeo and Juliet?",
      correct_answer: "William Shakespeare",
      incorrect_answers: ["Charles Dickens", "Mark Twain", "Jane Austen"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "History",
      question: "What year did World War II end?",
      correct_answer: "1945",
      incorrect_answers: ["1943", "1944", "1946"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "Science & Nature",
      question: "What is the chemical symbol for gold?",
      correct_answer: "Au",
      incorrect_answers: ["Ag", "Fe", "Cu"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Math",
      question: "How many sides does a hexagon have?",
      correct_answer: "Six",
      incorrect_answers: ["Five", "Seven", "Eight"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Math",
      question: "What is the smallest prime number?",
      correct_answer: "Two",
      incorrect_answers: ["One", "Three", "Zero"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "Science & Nature",
      question: "Which planet is closest to the Sun?",
      correct_answer: "Mercury",
      incorrect_answers: ["Venus", "Earth", "Mars"],
    },
    {
      type: "multiple",
      difficulty: "easy",
      category: "General Knowledge",
      question: "What is the main ingredient in guacamole?",
      correct_answer: "Avocado",
      incorrect_answers: ["Tomato", "Cucumber", "Pepper"],
    },
    {
      type: "multiple",
      difficulty: "medium",
      category: "History",
      question: "In what country did the Renaissance begin?",
      correct_answer: "Italy",
      incorrect_answers: ["France", "England", "Spain"],
    },
  ],
};

export default SAMPLE_FLASHCARDS;
